import React, {useState, useEffect }  from 'react';
//import {CanvasJSChart} from 'canvasjs-react-charts';
import TableChart_Group from '../../../compoment/table/TableChart_Group.js';


const DataAllCompany =(props) =>{
    const [dataTable, setDataTable] = useState(
        [{'table': 'users',
            'mode': 1,
            'optionAll': 'Số lượng Người dùng thêm vào',
            'option1year': 'Số lượng Người dùng thêm vào',
            'last7day': 'Số lượng Người dùng 1 tuần gần nhất',
            'table_name': 'Người dùng'},
           {'table': 'adress',
            'mode': 1,
            'optionAll': 'Số lượng Địa chỉ thêm vào',
            'option1year': 'Số lượng Địa chỉ thêm vào',
            'last7day': 'Số lượng Địa chỉ 1 tuần gần nhất',
            'table_name': 'Địa chỉ'},
           {'table': 'group_content',
            'mode': 1,
            'optionAll': 'Số lượng Nhóm bài báo thêm vào',
            'option1year': 'Số lượng Nhóm bài báo thêm vào',
            'last7day': 'Số lượng Nhóm bài báo 1 tuần gần nhất',
            'table_name': 'Nhóm bài báo'},
           {'table': 'mqtt_microservice',
            'mode': 1,
            'optionAll': 'Số lượng Dịch vụ MQTT thêm vào',
            'option1year': 'Số lượng Dịch vụ MQTT thêm vào',
            'last7day': 'Số lượng Dịch vụ MQTT 1 tuần gần nhất',
            'table_name': 'Dịch vụ MQTT'},
           {'table': 'mqtt_user',
            'mode': 1,
            'optionAll': 'Số lượng Người dùng MQTT thêm vào',
            'option1year': 'Số lượng Người dùng MQTT thêm vào',
            'last7day': 'Số lượng Người dùng MQTT 1 tuần gần nhất',
            'table_name': 'Người dùng MQTT'},
           {'table': 'gro_pages_content',
            'mode': 1,
            'optionAll': 'Số lượng Bài báo thêm vào',
            'option1year': 'Số lượng Bài báo thêm vào',
            'last7day': 'Số lượng Bài báo 1 tuần gần nhất',
            'table_name': 'Bài báo'},
           {'table': 'group_content_sub',
            'mode': 1,
            'optionAll': 'Số lượng Nhóm bài báo phụ thêm vào',
            'option1year': 'Số lượng Nhóm bài báo phụ thêm vào',
            'last7day': 'Số lượng Nhóm bài báo phụ 1 tuần gần nhất',
            'table_name': 'Nhóm bài báo phụ'},
           {'table': 'product_back',
            'mode': 1,
            'optionAll': 'Số lượng Sản phẩm trả lại thêm vào',
            'option1year': 'Số lượng Sản phẩm trả lại thêm vào',
            'last7day': 'Số lượng Sản phẩm trả lại 1 tuần gần nhất',
            'table_name': 'Sản phẩm trả lại'},
           {'table': 'service_bill',
            'mode': 1,
            'optionAll': 'Số lượng Hóa đơn dịch vụ thêm vào',
            'option1year': 'Số lượng Hóa đơn dịch vụ thêm vào',
            'last7day': 'Số lượng Hóa đơn dịch vụ 1 tuần gần nhất',
            'table_name': 'Hóa đơn dịch vụ'},
           {'table': 'product_buy',
            'mode': 1,
            'optionAll': 'Số lượng Hóa đơn mua hàng thêm vào',
            'option1year': 'Số lượng Hóa đơn mua hàng thêm vào',
            'last7day': 'Số lượng Hóa đơn mua hàng 1 tuần gần nhất',
            'table_name': 'Hóa đơn mua hàng'},
           {'table': 'product_buy_detail',
            'mode': 1,
            'optionAll': 'Số lượng Chi tiết sản phẩm mua thêm vào',
            'option1year': 'Số lượng Chi tiết sản phẩm mua thêm vào',
            'last7day': 'Số lượng Chi tiết sản phẩm mua 1 tuần gần nhất',
            'table_name': 'Chi tiết sản phẩm mua'},
           {'table': 'service_charging',
            'mode': 1,
            'optionAll': 'Số lượng Nạp dịch vụ thêm vào',
            'option1year': 'Số lượng Nạp dịch vụ thêm vào',
            'last7day': 'Số lượng Nạp dịch vụ 1 tuần gần nhất',
            'table_name': 'Nạp dịch vụ'},
           {'table': 'company',
            'mode': 1,
            'optionAll': 'Số lượng Công ty thêm vào',
            'option1year': 'Số lượng Công ty thêm vào',
            'last7day': 'Số lượng Công ty 1 tuần gần nhất',
            'table_name': 'Công ty'},
           {'table': 'customer',
            'mode': 1,
            'optionAll': 'Số lượng Khách hàng thêm vào',
            'option1year': 'Số lượng Khách hàng thêm vào',
            'last7day': 'Số lượng Khách hàng 1 tuần gần nhất',
            'table_name': 'Khách hàng'},
           {'table': 'detailbank',
            'mode': 1,
            'optionAll': 'Số lượng Ngân hàng thêm vào',
            'option1year': 'Số lượng Ngân hàng thêm vào',
            'last7day': 'Số lượng Ngân hàng 1 tuần gần nhất',
            'table_name': 'Ngân hàng'},
           {'table': 'enterprise',
            'mode': 1,
            'optionAll': 'Số lượng Doanh nghiệp thêm vào',
            'option1year': 'Số lượng Doanh nghiệp thêm vào',
            'last7day': 'Số lượng Doanh nghiệp 1 tuần gần nhất',
            'table_name': 'Doanh nghiệp'},
           {'table': 'product_lost',
            'mode': 1,
            'optionAll': 'Số lượng Mất sản phẩm thêm vào',
            'option1year': 'Số lượng Mất sản phẩm thêm vào',
            'last7day': 'Số lượng Mất sản phẩm 1 tuần gần nhất',
            'table_name': 'Mất sản phẩm'},
           {'table': 'product',
            'mode': 1,
            'optionAll': 'Số lượng Sản phẩm thêm vào',
            'option1year': 'Số lượng Sản phẩm thêm vào',
            'last7day': 'Số lượng Sản phẩm 1 tuần gần nhất',
            'table_name': 'Sản phẩm'},
           {'table': 'return_service',
            'mode': 1,
            'optionAll': 'Số lượng Dịch vụ trả lại thêm vào',
            'option1year': 'Số lượng Dịch vụ trả lại thêm vào',
            'last7day': 'Số lượng Dịch vụ trả lại 1 tuần gần nhất',
            'table_name': 'Dịch vụ trả lại'},
           {'table': 'service',
            'mode': 1,
            'optionAll': 'Số lượng Dịch vụ thêm vào',
            'option1year': 'Số lượng Dịch vụ thêm vào',
            'last7day': 'Số lượng Dịch vụ 1 tuần gần nhất',
            'table_name': 'Dịch vụ'},
           {'table': 'product_store',
            'mode': 1,
            'optionAll': 'Số lượng Kho hàng thêm vào',
            'option1year': 'Số lượng Kho hàng thêm vào',
            'last7day': 'Số lượng Kho hàng 1 tuần gần nhất',
            'table_name': 'Kho hàng'},
           {'table': 'advertisement_content',
            'mode': 1,
            'optionAll': 'Số lượng Bài báo quảng bá thêm vào',
            'option1year': 'Số lượng Bài báo quảng bá thêm vào',
            'last7day': 'Số lượng Bài báo quảng bá 1 tuần gần nhất',
            'table_name': 'Bài báo quảng bá'},
           {'table': 'product_image',
            'mode': 1,
            'optionAll': 'Số lượng Hình ảnh sản phẩm thêm vào',
            'option1year': 'Số lượng Hình ảnh sản phẩm thêm vào',
            'last7day': 'Số lượng Hình ảnh sản phẩm 1 tuần gần nhất',
            'table_name': 'Hình ảnh sản phẩm'},
           {'table': 'service_group',
            'mode': 1,
            'optionAll': 'Số lượng Nhóm dịch vụ thêm vào',
            'option1year': 'Số lượng Nhóm dịch vụ thêm vào',
            'last7day': 'Số lượng Nhóm dịch vụ 1 tuần gần nhất',
            'table_name': 'Nhóm dịch vụ'},
           {'table': 'stock_name',
            'mode': 1,
            'optionAll': 'Số lượng Tên cổ phiếu thêm vào',
            'option1year': 'Số lượng Tên cổ phiếu thêm vào',
            'last7day': 'Số lượng Tên cổ phiếu 1 tuần gần nhất',
            'table_name': 'Tên cổ phiếu'},
           {'table': 'stock_sale',
            'mode': 1,
            'optionAll': 'Số lượng Bán cổ phiếu thêm vào',
            'option1year': 'Số lượng Bán cổ phiếu thêm vào',
            'last7day': 'Số lượng Bán cổ phiếu 1 tuần gần nhất',
            'table_name': 'Bán cổ phiếu'},
           {'table': 'stock_buy',
            'mode': 1,
            'optionAll': 'Số lượng Mua cổ phiếu thêm vào',
            'option1year': 'Số lượng Mua cổ phiếu thêm vào',
            'last7day': 'Số lượng Mua cổ phiếu 1 tuần gần nhất',
            'table_name': 'Mua cổ phiếu'},
           {'table': 'product_pages',
            'mode': 1,
            'optionAll': 'Số lượng Trang sản phẩm thêm vào',
            'option1year': 'Số lượng Trang sản phẩm thêm vào',
            'last7day': 'Số lượng Trang sản phẩm 1 tuần gần nhất',
            'table_name': 'Trang sản phẩm'},
           {'table': 'service_pages',
            'mode': 1,
            'optionAll': 'Số lượng Trang dịch vụ thêm vào',
            'option1year': 'Số lượng Trang dịch vụ thêm vào',
            'last7day': 'Số lượng Trang dịch vụ 1 tuần gần nhất',
            'table_name': 'Trang dịch vụ'},
           {'table': 'product_group',
            'mode': 1,
            'optionAll': 'Số lượng Nhóm sản phẩm thêm vào',
            'option1year': 'Số lượng Nhóm sản phẩm thêm vào',
            'last7day': 'Số lượng Nhóm sản phẩm 1 tuần gần nhất',
            'table_name': 'Nhóm sản phẩm'},
           {'table': 'company_of_customer',
            'mode': 1,
            'optionAll': 'Số lượng Công ty của khách hàng thêm vào',
            'option1year': 'Số lượng Công ty của khách hàng thêm vào',
            'last7day': 'Số lượng Công ty của khách hàng 1 tuần gần nhất',
            'table_name': 'Công ty của khách hàng'},
           {'table': 'cost_transport',
            'mode': 1,
            'optionAll': 'Số lượng Chi phí vận chuyển thêm vào',
            'option1year': 'Số lượng Chi phí vận chuyển thêm vào',
            'last7day': 'Số lượng Chi phí vận chuyển 1 tuần gần nhất',
            'table_name': 'Chi phí vận chuyển'},
           {'table': 'payment_type',
            'mode': 1,
            'optionAll': 'Số lượng Loại thanh toán thêm vào',
            'option1year': 'Số lượng Loại thanh toán thêm vào',
            'last7day': 'Số lượng Loại thanh toán 1 tuần gần nhất',
            'table_name': 'Loại thanh toán'},
           {'table': 'payment_internal',
            'mode': 1,
            'optionAll': 'Số lượng Thanh toán nội bộ thêm vào',
            'option1year': 'Số lượng Thanh toán nội bộ thêm vào',
            'last7day': 'Số lượng Thanh toán nội bộ 1 tuần gần nhất',
            'table_name': 'Thanh toán nội bộ'},
           {'table': 'payment_transport',
            'mode': 1,
            'optionAll': 'Số lượng Thanh toán vận chuyển thêm vào',
            'option1year': 'Số lượng Thanh toán vận chuyển thêm vào',
            'last7day': 'Số lượng Thanh toán vận chuyển 1 tuần gần nhất',
            'table_name': 'Thanh toán vận chuyển'},
           {'table': 'advertisement_product',
            'mode': 1,
            'optionAll': 'Số lượng Sản phẩm quảng cáo thêm vào',
            'option1year': 'Số lượng Sản phẩm quảng cáo thêm vào',
            'last7day': 'Số lượng Sản phẩm quảng cáo 1 tuần gần nhất',
            'table_name': 'Sản phẩm quảng cáo'},
           {'table': 'social_user',
            'mode': 1,
            'optionAll': 'Số lượng Người dùng mạng xã hội thêm vào',
            'option1year': 'Số lượng Người dùng mạng xã hội thêm vào',
            'last7day': 'Số lượng Người dùng mạng xã hội 1 tuần gần nhất',
            'table_name': 'Người dùng mạng xã hội'},
           {'table': 'group_company',
            'mode': 1,
            'optionAll': 'Số lượng Nhóm công ty thêm vào',
            'option1year': 'Số lượng Nhóm công ty thêm vào',
            'last7day': 'Số lượng Nhóm công ty 1 tuần gần nhất',
            'table_name': 'Nhóm công ty'},
           {'table': 'group_company_detail',
            'mode': 1,
            'optionAll': 'Số lượng Chi tiết nhóm công ty thêm vào',
            'option1year': 'Số lượng Chi tiết nhóm công ty thêm vào',
            'last7day': 'Số lượng Chi tiết nhóm công ty 1 tuần gần nhất',
            'table_name': 'Chi tiết nhóm công ty'},
           {'table': 'social_shop',
            'mode': 1,
            'optionAll': 'Số lượng Cửa hàng mạng xã hội thêm vào',
            'option1year': 'Số lượng Cửa hàng mạng xã hội thêm vào',
            'last7day': 'Số lượng Cửa hàng mạng xã hội 1 tuần gần nhất',
            'table_name': 'Cửa hàng mạng xã hội'}]
        
    );
        const [dataTableResponse, setDataTableResponse] = useState([]);

    


    return (
        <div className="user-data">
            <div> Bảng báo cáo Doanh số</div>

                    {dataTable.map((info) => (
                        <TableChart_Group table={info} title_table=""  />
                         
                )           
            )}
           
        </div>
    );
};
// <CanvasJSChart options = {dataOption}/>
//
export default DataAllCompany;